name: mahjong-quest
services:
  gateway:
    build:
      context: ../MQGateway
    environment:
      - GATEWAY_PORT=${GATEWAY_PORT}
      - AUTHENTICATION_PORT=${AUTHENTICATION_PORT}
      - AUTHENTICATION_URL=${AUTHENTICATION_URL}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
      - "${GATEWAY_PORT}:${GATEWAY_PORT}/udp"
    volumes:
      - ../MQGateway/dist:/dist
    entrypoint: ["/dist/MQGateway.x86_64", "--headless"]
    networks:
      - mahjong-quest-network
    tty: true
  authentication:
    build:
      context: ../MQAuthentication
    environment:
      - AUTHENTICATION_PORT=${AUTHENTICATION_PORT}
      - GAMEHUB_PORT=${GAMEHUB_PORT}
    ports:
      - "${AUTHENTICATION_PORT}:${AUTHENTICATION_PORT}"
      - "${AUTHENTICATION_PORT}:${AUTHENTICATION_PORT}/udp"
      - "${GAMEHUB_PORT}:${GAMEHUB_PORT}"
      - "${GAMEHUB_PORT}:${GAMEHUB_PORT}/udp"
    volumes:
      - ../MQAuthentication/dist:/dist
    entrypoint: ["/dist/MQAuthentication.x86_64", "--headless"]
    networks:
      - mahjong-quest-network
    tty: true
  game:
    build:
      context: ../MQGame
    environment:
      - GAME_PORT=${GAME_PORT}
      - GAMEHUB_PORT=${GAMEHUB_PORT}
      - AUTHENTICATION_URL=${AUTHENTICATION_URL}
    ports:
      - "${GAME_PORT}:${GAME_PORT}"
      - "${GAME_PORT}:${GAME_PORT}/udp"
    volumes:
      - ../MQGame/dist:/dist
    entrypoint: ["/dist/MQGame.x86_64", "--headless"]
    networks:
      - mahjong-quest-network
    tty: true
networks:
  mahjong-quest-network:
    driver: bridge